// AUTO-GENERATED by scripts/generate-gallery-thumbs.mjs -- do not edit manually
// Run: npm run thumbs (from harsha-portfolio/) to regenerate after changing gallery assets

export interface GalleryThumb {
  thumbSrc: string
  blurDataURL: string
}

export const galleryThumbs: Record<string, GalleryThumb> = {
  "isso-arrive-and-thrive": {
    "thumbSrc": "/gallery/digital-signage/isso-arrive-and-thrive-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoMAAcAAsBMJbACdAELKVDPAAD+jrz6xslS5y0zx9SKzbFnKxpOfQAA"
  },
  "oie-study-abroad": {
    "thumbSrc": "/gallery/linkedin-posts/oie-study-abroad-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoMAAoAAsBMJbACsAEf3QRuIgAA/ut5QhY3yi/wZakH77Xr7zD4V1uR/5gAAA=="
  },
  "ic-black-history-month": {
    "thumbSrc": "/gallery/instagram-posts/ic-black-history-month-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoMAA8AAsBMJYgCdAEO/0+FgAD++JOIVinvDmXaTE80+TzUCnDbbR7cAAA="
  },
  "ic-seasons-greeting-card": {
    "thumbSrc": "/gallery/instagram-posts/ic-seasons-greeting-card-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoMAA8AAsBMJQBOgCHQSBVkwAD+8zk08k78xTDGrZ/cHj4kzG5P6c6oicCiyBgA"
  },
  "ii-dir-lunch": {
    "thumbSrc": "/gallery/instagram-posts/ii-dir-lunch-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoMAA8AAsBMJZQCdAEO4qOuwgAA/trQ66kY9NpILzdS9/KTxsREoAAA"
  },
  "ii-francisco-dinner": {
    "thumbSrc": "/gallery/instagram-posts/ii-francisco-dinner-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoMABEAPtFUpEuoJKOhsAgBABoJQBdgBDmkrO8bO+8yQAD+0OlV+HjUJUFbPGsgfAfknWECNSNXrMU6kGX64gb/rh8YAA=="
  },
  "isso-pizza-and-plagiarism": {
    "thumbSrc": "/gallery/instagram-posts/isso-pizza-and-plagiarism-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoMAA8AAsBMJQBOgCHhaSxflMAA/vgYqF61tU8XH5QPhQ/gefZHiEv34rEGZF2c5Y4AAA=="
  },
  "isso-townhall-meeting": {
    "thumbSrc": "/gallery/instagram-posts/isso-townhall-meeting-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoMAA8AAsBMJQBOgCIjN7cJOLAA/idsUs9kBxmRW6knfhlBq/UXKkURYLbXIkAA"
  },
  "isso-us-port-of-entry-webinar": {
    "thumbSrc": "/gallery/instagram-posts/isso-us-port-of-entry-webinar-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoMAAoAAsBMJQBOgCHHb3MAAP0v3Ep4UUWOniLaDSVl6gIAAAA="
  },
  "oie-slice-of-study-abroad": {
    "thumbSrc": "/gallery/instagram-posts/oie-slice-of-study-abroad-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoMAA8AAsBMJZACdADbHClZwAD+8W7Fxdw1lM8W77jsF5czFd5EbXH7AOq971j6pVl9iEUqFiYqSnysAAA="
  },
  "pp-real-id": {
    "thumbSrc": "/gallery/instagram-posts/pp-real-id-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoMAA8AAsBMJaACdAD0iXUbBgAA/tDxJFHX64rGVxEADrWHsOgSSd2wj+E/AAAA"
  },
  "utdg-last-call-deadline": {
    "thumbSrc": "/gallery/instagram-posts/utdg-last-call-deadline-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoMAA8AAsBMJYgCdAEO/C0zIAD+7EKH0ABcIs00QoWn+dmvTlsJgAQAAAA="
  },
  "utdg-pre-masters-pathway-ad-1": {
    "thumbSrc": "/gallery/linkedin-ads/utdg-pre-masters-pathway-ad-1-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACQAQCdASoMAAYAAsBMJZgCdAEOBAAA/rI5W+/+YYbeaF+TXJEUcAAA"
  },
  "utdg-scholarships-ad-1": {
    "thumbSrc": "/gallery/linkedin-ads/utdg-scholarships-ad-1-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoMAAYAAsBMJaACdADaPHbQAM2TbsYtx7jY22Kczue/iDY38fOtw8QiWazAAA=="
  },
  "utdg-scholarships-ad-2": {
    "thumbSrc": "/gallery/linkedin-ads/utdg-scholarships-ad-2-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoMAAYAAsBMJQBYdhtmBcWvwAD1PUs43WbEAt2diU1kN1ycohtAAA=="
  },
  "utdg-scholarships-ad-3": {
    "thumbSrc": "/gallery/linkedin-ads/utdg-scholarships-ad-3-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoMAAYAAsBMJYwCdADc73jWgAD+1Q4mVOqvQaK+4eGhTj0F7rssUmAA"
  },
  "isso-lets-talk": {
    "thumbSrc": "/gallery/linkedin-events/isso-lets-talk-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoMAAcAAsBMJagCdADzmXgAAP7jS2AKiMmQrdIyu2zEZ8nnju78U7EAAAA="
  },
  "utd-pre-masters-pathway": {
    "thumbSrc": "/gallery/linkedin-events/utd-pre-masters-pathway-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoMAAYAAsBMJQBOgBud74LkAP59N89SnsyAoaSE7GRmq7czhYUDMvd1q9PAAA=="
  },
  "ic-international-youth-day": {
    "thumbSrc": "/gallery/linkedin-posts/ic-international-youth-day-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAAoAAsBMJQBOgCHhgNpHAAD+8C/568OMO/XMRcW2ENd3ECAbGTrDoAAAAA=="
  },
  "ic-national-hispanic-heritage-month": {
    "thumbSrc": "/gallery/linkedin-posts/ic-national-hispanic-heritage-month-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoMAAoAAsBMJQBOgCFr54QeAAD+wHdKYvNHP/GO7+4g9PF18NQOJFAA"
  },
  "ic-weeks-of-welcome": {
    "thumbSrc": "/gallery/linkedin-posts/ic-weeks-of-welcome-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAABwAQCdASoMAAoAAsBMJYwCdAFAAAD+8aubC3XsHyyYi5/2AWAAAA=="
  },
  "ic-welcome-back-to-campus": {
    "thumbSrc": "/gallery/linkedin-posts/ic-welcome-back-to-campus-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoMAAoAAsBMJZQCdAEK3xk/1QAA/jBbDJcgG3YqcQGmEGqJe3UiAAAA"
  },
  "ic-womens-equality-day": {
    "thumbSrc": "/gallery/linkedin-posts/ic-womens-equality-day-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoMAAoAAsBMJQBOgCIfU6fGtvAA/sGBie5sIpRRs0chwz8si9bkTdgYAAA="
  },
  "isso-raising-cans": {
    "thumbSrc": "/gallery/linkedin-posts/isso-raising-cans-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAAwAAsBMJYgCdAEOsAvjgAD++Bzwxk2ecByghibRTmnRg7asKSuPjvAAAA=="
  },
  "ic-donor-thank-you-cards": {
    "thumbSrc": "/gallery/printables/ic-donor-thank-you-cards-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACwAQCdASoMAAcAAsBMJZQCdAEOGWIAAPY6QcJL/rmzz9EEJgAAAA=="
  },
  "ic-iew-poster": {
    "thumbSrc": "/gallery/printables/ic-iew-poster-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADwAQCdASoMABAAAsBMJYwC7AEO4dCMb9AA/viVCADb3Z2N+/+7bQ549lGrq3t+V0I29Exvk4AAAA=="
  },
  "ic-independence-day-poster": {
    "thumbSrc": "/gallery/printables/ic-independence-day-poster-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMABAAAsBMJZACdAEOUcqvXAD+u7Ndf2W5HxRnsg0nlaS0QG6inbz2y6/vLzAAAAA="
  },
  "ic-juneteenth-poster": {
    "thumbSrc": "/gallery/printables/ic-juneteenth-poster-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMABAAAsBMJbACdAEOZchHAAD+pkr7iBr4yk9+AGT0u/+Tl7ssIIner3hGY+FcW+IXAAAA"
  },
  "oics-brochure-refined": {
    "thumbSrc": "/gallery/printables/oics-brochure-refined-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4WAoAAAAQAAAACwAACAAAQUxQSCQAAAABJ0CQbePPvO3XiIj4EigEgIZJIYUUUsifatcgov+Z4qLCgidWUDggMAAAALABAJ0BKgwACQACwEwliAJ0ANr40AAAziSDt5+Pwm1rvGxXrlVDv3bOWl3cvRrAAA=="
  },
  "utdg-pre-masters-pathway-brochure": {
    "thumbSrc": "/gallery/printables/utdg-pre-masters-pathway-brochure-thumb.webp",
    "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4WAoAAAAQAAAACwAACAAAQUxQSCQAAAABJ0CQbePPvO3XiIj4EigEgIZJIYUUUsifatcgov+Z4qLCgidWUDggKgAAANABAJ0BKgwACQACwEwljAJ0AQ77EU4AAP6jBNFtyKbbEqYs7XE168PAAA=="
  }
}

export function getThumb(src: string): GalleryThumb | undefined {
  const key = src.split('/').pop()?.replace(/\.(png|webp|jpg|jpeg)$/, '')
  return key ? galleryThumbs[key] : undefined
}
